config/routes.rb
Rails.application.routes.draw do
  root "pages#start"
  get 'about', to: "pages#about"
  resources :articles
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  post '/articles/:id', to: 'comments#create'
  resources :comments 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user 
	has_many :article_categories
	has_many :comments, dependent: :destroy
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: { minimum: 3, maximum: 100 }
 	validates :description, presence: true, length: { minimum: 5, maximum: 500 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, length: {minimum: 3, maximum: 25}
	validates_uniqueness_of :name
	has_many :article_categories
	has_many :articles, through: :article_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
	 validates :description, presence: true, length: { minimum: 1, maximum: 1000 }
	 belongs_to :user
  	 belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
	self.per_page = 4
end

app/models/user.rb
class User < ApplicationRecord 
	before_save { self.email = email.downcase }
	has_many :comments, dependent: :destroy
	has_many :articles, dependent: :destroy
	validates :username, presence: true, 
						 uniqueness: { case_sensitive: false }, 
						 length: {minimum:3, maximum:25}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, 
					  length: {maximum:105}, 
					  uniqueness: { case_sensitive: false },
					  format: {with: VALID_EMAIL_REGEX }

	has_secure_password
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user, :is_logged_in, :category_icon_select
	
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def is_logged_in
		!!current_user
	end

	def require_user
		if !is_logged_in
			flash[:alert] = "You need to be signed in to perform this action"
			redirect_to login_path
		end
	end

	def category_icon_select(category)

		if category == "Music"
			return "music"
		end

		if category == "Sports"
			return "sports"
		end

		if category == "Medicine"
			return "medicine"
		end

		if category == "Travel"
			return "travel" 
		end

		if category == "Food"
			return "food"
		end

	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update]

	def show
		@comments = Comment.all 
	end

	def index
		@articles = Article.paginate(page: params[:page], per_page: 3)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_param)
		@article.user = current_user
		if @article.save
			flash[:notice] = "Note was created successfully."
			redirect_to current_user
		else
			render "new"
		end
	end

	def edit
	end

	def update
		if @article.update(article_param)
			flash[:notice] = "Note was updated successfully"
			redirect_to @article
		else
			render "edit"
		end

	end 

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to @article
	end

	private

		def set_article
			@article = Article.find(params[:id]) 
		end

		def article_param
			params.require(:article).permit(:title, :description, category_ids:[])
		end

		def require_same_user
			if (current_user != @article.user) && !(current_user.admin?)
				flash[:alert] = "You need to be logged in to your own profile to perform this action"
				redirect_to @article
			end
		end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
	before_action :set_category, only: [:show, :edit, :update]
	before_action :require_user, :require_admin, except: [:index, :show]

	def show
	end

	def index
		@categories = Category.paginate(page: params[:page], per_page: 3)
	end

	def new
		@category = Category.new()
	end  

	def create 
		@category = Category.new(categories_params)
		if @category.save
			flash[:notice] = "Category successfully created"
			redirect_to @category
		else
			render 'new'
		end
	end

	private

	def categories_params
		params.require(:category).permit(:name)
	end

	def set_category
		@category = Category.find(params[:id])
	end

	def require_admin
		if !current_user.admin? 
			flash[:error] = "You need to have admin access to do this"
			redirect_to current_user
		end 
	end

end 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_same_user, only: [:delete]
	before_action :require_user, only: [:create]

	def show
	end

	def new
	end

	def index
		@comments = Comment.all 
	end

	def destroy
      @comment = Comment.find(params[:id])
      @article = Article.find(@comment.article_id)
      @comment.destroy
      redirect_to article_path(@article)
	end


	def create
		@article = Article.find(params[:id])
		@comment = @article.comments.new(comment_param)
		@comment.user_id = current_user.id
		
		if @comment.save
			flash[:notice] = "Comment saved successfully."
			redirect_to article_path(@article)
		else
			flash[:error] = "Error saving comment"
			redirect_to article_path(@article)
		end
	end

	private 

		def comment_param
			params.permit(:description)
		end

		def require_same_user
			if (current_user.id != @comment.user_id) && !(current_user.admin?)
				flash[:alert] = "You need to be logged in to your own profile to perform this action"
				redirect_to @article
			end
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def start
		redirect_to articles_path if is_logged_in
	end

	def about
	end

	def signup
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id 
			flash[:alert] = "Logged in successfully"
			redirect_to user
		else
			flash.now[:error] = "There was something wrong"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:alert] = 'You have been successfully logged out'
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show, :destroy]
	before_action :require_user, only: [:edit, :update]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 3)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_param)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "Welcome to the site #{@user.username}."
			redirect_to articles_path
		else
			render "new"
		end
	end 

	def edit
	end

	def update
		if @user.update(user_param)
			flash[:notice] = "Your changes were saved"
			redirect_to @user
		else
			render "edit"
		end
	end

	def show
		@articles = @user.articles.paginate(page: params[:page], per_page: 3)
	end

	def login
	end

	def destroy
		@user.destroy
		if !(current_user.admin?)
			session[:user_id] = nil 
		end
		flash[:notice] = "All information associated with the user has been deleted"
		redirect_to articles_path
	end

	private

		def set_user
			@user = User.find(params[:id]) 
		end

		def user_param
			params.require(:user).permit(:username, :email, :password)
		end

		def require_same_user
			if current_user != @user && !(current_user.admin?)
				flash[:alert] = "You need to be logged in to your own profile to perform this action"
				redirect_to @user
			end
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
  <div class="container">
	  <% @articles.each do |article| %>
	    <div class="row justify-content-center">
	      <div class="col-8 mt-4">
	        <div class="card text-center shadow mb-5 bg-white rounded" style = "border-color: #6c757d;">
	          <div class="card-header font-italic bg-light text-muted d-flex justify-content-center" style = "display:flex">
	            by <%=article.user.username if article.user%>
	            <div class = icon-placement>
	             		<%article.categories.each do |category|%>
		           		<div class = <%="#{category_icon_select(category.name)}-icon"%> > </div>
	            		<%end%>
	        	</div>
	          </div>
	          
	          <div class="card-body">
	            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-on-white" %></h5>
	            <p class="card-text"><%= simple_format(truncate(article.description, length: 100)) %></p>
	            
	            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
	            <% if is_logged_in && (article.user == current_user || current_user.admin?) %>
	            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-success" %>
	            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
	            <%end%>
	          </div>

	          <div class="card-footer bg-light text-muted">
	            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
	            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
	          </div>
	        </div>
	      </div>
	    </div>
	  <% end %>
	  </div>
	</div>  

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |f| %>
<%= render 'pages/shared/errors', obj: @article %>
<div class = "container pt-5 pl-5 pr-5 pb-3 mb-2 bg-light text-white col-7 shadow" id ="form-container">
	<div class = "form group text-center ">
		<p> 
			<%= f.text_field :title, class: "form-control shadow", placeholder: "Enter a title" %>
		</p>

		<p>
			<%=f.text_area :description, rows:8, class: "form-control shadow", placeholder: "Enter your note"  %>
		</p>

		<p>
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b|%>
				 <%= b.label class:"text-on-white p-1" do%>
	         	 	<%=b.check_box + " " + b.text%>
	        	 <%end%>
    		<% end %>
		</p>

		<p>
			<%=f.submit(@article.new_record? ? "Create Note" : "Update Note", class:"btn btn-outline-success btn-md") %>
		</p>


		<% end %>
	</div>
</div>

<p style = "text-align: center"><%=link_to 'Canel and Return Home', articles_path, class: "text-on-grape"%></p>

app/views/articles/edit.html.erb
<h1 class = "text-center mt-4 text-on-grape"> Edit Note </h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class = "text-center mt-4 text-on-grape"> Notes </h1>
<%= render 'article' %>


<div id = "page-content">
	<div class = "apple_pagination">
		<%= will_paginate @articles, :container => false  %>
	</div>
</div>

app/views/articles/new.html.erb
<h1 class = "text-center text-on-grape mt-4"> New Note </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
	<h1 class = "text-center mt-4 text-on-grape"> <%= @article.title %> </h1>
		 <div class="row justify-content-center">
			      <div class="col-8 mt-4">
			        <div class="card text-center shadow mb-5 bg-white rounded" style = "border-color: #6c757d;">
			          <div class="card-header font-italic bg-light text-muted">
			            by <%=@article.user.username%> 
			          </div>

			           <div class = 'row justify-content-center mt-2'>
				            <%@article.categories.each do |category|%>
				           	<div class = <%="#{category_icon_select(category.name)}-icon"%> > </div>
				            <%end%>
	        			</div>

			          <div class="card-body show-pad">
			            <div class="card-text"><%= simple_format(@article.description) %></div>
			            <% if (is_logged_in) && ((@article.user == current_user) || current_user.admin?)  %>
			            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-success" %>
			            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
			            <%end%>
			          </div>
			          <div class="card-footer bg-light text-muted">
			            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
			            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
			          </div>
			        </div>
			      </div>
			    </div>
			    <p style = "text-align: center"><%=link_to 'Back', articles_path, class: "mb-2 text-on-grape"%></p>

	<h3 class = "text-on-grape pt-4" style = "margin-left:10px">Leave a Comment </h3>		    
			    <%= render 'comments/form' %>
			    <%= render 'comments/comment_view', :comment => @comments, :article => @article%>

app/views/categories/index.html.erb
  <h1 class = "text-center mt-4 text-on-grape"> Categories </h1>
	  <div class="container">
		  <% @categories.each do |category| %>
		    <div class="row justify-content-center">
		      <div class="col-6 mt-4">
		        <div class="card text-center shadow mb-5 bg-white rounded" style = "border-color: #6c757d;">
		          <div class="card-header font-italic bg-light text-muted">
		          </div>
		          <div class="card-body">
		            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-on-white" %></h5>

		             <div class = 'row justify-content-center'>
			           		<div class = <%="#{category_icon_select(category.name)}-icon"%> > </div>
	       			 </div>
		          </div>
		          <div class="card-footer bg-light text-muted">
		            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
		            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
		          </div>
		        </div>
		      </div>
		    </div>
		  <% end %>
		  </div>
		</div>  	
		
<div id = "page-content">
	<div class = "apple_pagination">
		<%= will_paginate @categories, :container => false  %>
	</div>
</div>

app/views/categories/new.html.erb
<h1 class = "text-center mt-4 text-dark"> Create New Category </h1>
<%= form_with(model: @category, local: true) do |f| %>
<%= render 'pages/shared/errors', obj: @category %>
<div class = "container p-3 mb-2 bg-light text-white col-6 shadow" id ="form-container-signup">
	<div class = "form group text-center">
		<p> 
			<%= f.text_field :name, class: "form-control shadow", placeholder: "Enter Category Name" %>
		</p>

		<p>
			<%=f.submit class:"btn btn-outline-success btn-lg login_signup_button" %>
		</p>
		<% end %>
	</div>
</div>

<p style = "text-align: center">
	<% if is_logged_in %>
		<%=link_to 'Canel and Return Home', articles_path, class: "text-on-grape"%>
	<% else %>
		<%=link_to 'Canel and Return Home', root_path, class: "text-on-grape"%>
	<% end %>
</p>

app/views/categories/show.html.erb
<h1 class = "text-center mt-4 text-on-grape"><%= @category.name%></h1>

app/views/comments/_comment_view.html.erb
	  <div class = "comments-container">
	  <% @comments.each do |comment| %>
	  	<% if (comment.article_id == @article.id) %>
		    <div class="row">
		      <div class="col-12 mt-4">
		        <div class="card mb-3 comment-card">
		          <div class="card-body row pb-0 ">
		          	<div class = "avatar-icon"> </div>
		          	<div class = "comment-content">
			          	<h5 class = "text-on-grape"> <%=User.find(comment.user_id).username%> </h5>
			            <p class = "text-on-grape"> <%= comment.description %> </p>
			        </div>
			        <% if (is_logged_in) && (current_user.id == comment.user_id || current_user.admin?) %>
			        <%= link_to "x", comment_path(comment), class: "delete-margin mb-4 btn btn-light rounded-circle btn-sm", method: :delete, data: {confirm: "Are you sure?"} %>
			        <%end%>
		          </div>
		        </div>
		      </div>
		    </div>
		<%end%>
	
	 <% end %>
	</div>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
	<div class = "comments-container form group">
		<p>
			<%=f.text_area :description, rows:2, class: "col-12 comment-input-box" %>
		</p>
		<p class = "text-right">
			<%=f.submit class:"btn btn-light btn-sm" %>
		</p>
		<% end %>
	</div>

app/views/comments/index.html.erb
 <%= render 'comment_view' %> 

app/views/layouts/_footer.html.erb
 <footer id="sticky-footer" class="py-2 bg-dark text-white-50">
    <div class="container justify-content-center" style = "text-align:center">
      <small>Copyright &copy; Your Website &nbsp</small>
       <small> <a href = "https://icons8.com/" target="_blank" rel="noopener noreferrer">Icons by Icon8 </a> </small>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
 <%flash.each do |name,msg| %>
 <div style = "background-color: lightgrey">
 	<% if name == 'error' %>
 		<div class="alert alert-danger alert-dismissible fade show" role="alert">
	      <%= msg %>
	<% else %>     
	 	<div class="alert alert-success alert-dismissible fade show" role="alert">
	      <%= msg %>
	<%end%>
	   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	   <span aria-hidden="true">&times;</span>
	   </button>
	</div>
</div>
    <%end%>

app/views/layouts/_navbar.html.erb
  <nav class="safari_only navbar navbar-expand-lg navbar-light bg-light">
      <!-- <a class="navbar-brand" href="#">APP DEV</a> -->
      <%= link_to 'NOTES', root_path, class: "navbar-brand"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%=link_to 'Home', root_path, class: "nav-link"%>
          </li>

       <!--    <li class="nav-item">
            <%=link_to 'About', about_path, class: "nav-link"%>
          </li> -->

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Notes </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%=link_to 'View All Notes', articles_path, class: "dropdown-item"%>
               <% if is_logged_in %>
               <%=link_to 'Create a New Note', new_article_path, class: "dropdown-item"%>
               <% end %>
          </li>


          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Users </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%=link_to 'View All Users', users_path, class: "dropdown-item"%>
               <% if is_logged_in %>
               <%=link_to 'View Your Profile', current_user, class: "dropdown-item"%>
               <% end %>
          </li>

               <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Categories </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%=link_to 'View All Categories', categories_path, class: "dropdown-item"%>
               <% if is_logged_in && current_user.admin? %>
               <%=link_to 'Create new category', new_category_path, class: "dropdown-item"%>
               <% end %>
          </li>

        </ul>

        <ul class="navbar-nav ml-auto">
          <% if is_logged_in %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <%="(Admin) " if current_user.admin?%><%= current_user.username %> </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <%=link_to 'View your profile', current_user, class: "dropdown-item"%>
                      <%=link_to 'Logout', logout_path, class: "dropdown-item", method: :delete%>
                      <%=link_to 'Delete', user_path(current_user), class: "dropdown-item", method: :delete, data:{confirm: "Are you sure?"}%>
                    </div>
             </li>


             <%else%>
                <li class="nav-item">
                    <%=link_to 'Login', login_path, class: "nav-link"%>
                </li>
                <li class="nav-item">
                    <%=link_to 'Signup', signup_path, class: "nav-link"%>
                </li>

             <%end%>
           </ul>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class = "d-flex flex-column">
    <%= render 'layouts/navbar'%>
    <div id = "page-content">
    <%= render 'layouts/messages'%>
    <%= yield %>
    </div>
     <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<p> Welcome to the about page </p>

app/views/pages/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="container alert alert-danger col-7 alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">Errors:</h4>
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
	<ul>
		<% obj.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<%end%>
	</ul>
</div>
<%end%>

app/views/pages/start.html.erb
 <%= javascript_pack_tag 'custom.js' %>

    <div class = home-background>
    <div class = "container">
      <div class="text-center" style = "background-attachment: fixed;">  
        <h1>
          <a href="" style = "font-family:courier" class="mt-1 typewrite text-on-white" data-period="2000" data-type='[ "Why waste all that paper?", "When you can sign up for free!" ]'>
            <span class="wrap"></span>
          </a>
        </h1>
    <p><%= link_to "Sign up", signup_path, class: "mt-1 btn btn-outline-success btn-md"%></p>
      </div>
    </div>  
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
<%= render 'pages/shared/errors', obj: @user %>
<div class = "container p-3 mb-2 bg-light text-white col-6 shadow" id ="form-container-signup">
	<div class = "form group text-center">
		<p> 
			<%= f.text_field :username, class: "form-control shadow", placeholder: "Username" %>
		</p>

		<p>
			<%=f.email_field :email, class: "form-control shadow", placeholder: "Email" %>
		</p>

		<p>
			<%=f.password_field :password, class: "form-control shadow", placeholder: "Password" %>
		</p>

		<p>
			<%=f.submit(@user.new_record? ? "Signup" : "Update Accout", class:"btn btn-outline-success btn-lg login_signup_button") %>
		</p>


		<% end %>
	</div>
</div>

<p style = "text-align: center">
	<% if is_logged_in %>
		<%=link_to 'Canel and Return Home', articles_path, class: "text-on-grape"%>
	<% else %>
		<%=link_to 'Canel and Return Home', root_path, class: "text-on-grape"%>
	<% end %>
</p>

app/views/users/edit.html.erb
<h1 class = "text-on-grape text-center mt-4"> Edit your profile </h1>
<%= render 'form' %>

app/views/users/index.html.erb
  	<h1 class = "text-on-grape text-center mt-4"> Users </h1>
	  <div class="container">
	  <% @users.each do |user| %>
	    <div class="row justify-content-center">
	      <div class="col-8 mt-4">
	        <div class="card text-center shadow mb-5 bg-white rounded" style = "border-color: #6c757d;">
	          <div class="card-header font-italic bg-light">
	          	<%=user.username%>
	          </div>
	          <div class="card-body">
	          	<img src="https://cdn.pixabay.com/photo/2016/08/20/05/51/avatar-1606939_1280.png" width = "150px" height= "150px" alt="" class="rounded">
	            <p class="card-text pt-2"><%= pluralize(user.articles.count, "Article") %></p>
	            <%= link_to "View Profile", user_path(user), class: "btn btn-outline-success" %>
	            <% if (is_logged_in) %>
	            	<% if user == current_user%>
	           			 <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-success" %>
	            	<%end%>
	            	<% if current_user.admin? %>
	            	 	<%=link_to 'Delete Profile', user_path(user), class: "btn btn-outline-success", method: :delete, data:{confirm: "Are you sure?"}%>
	            	<%end%>
	            <%end%>	
	          </div>
	          <div class="card-footer bg-light text-muted">
	            <small class = "text-muted">Joined <%= time_ago_in_words(user.created_at) %> ago</small>
	          </div>
	        </div>
	      </div>
	    </div>
	  <% end %>
	  </div>
	</div> 

	<div id = "page-content">
	<div class = "apple_pagination">
		<%= will_paginate @articles, :container => false  %>
	</div>
</div>

app/views/users/new.html.erb
<h2 class = "text-on-grape text-center mt-4"> New User </h2>
<%= render 'form' %>

app/views/users/show.html.erb
<div class = "pt-4 text-center">
	<img src="https://cdn.pixabay.com/photo/2016/08/20/05/51/avatar-1606939_1280.png" width = "200px" height= "200px" alt="<%=@user.username %>" class="rounded"></br>
	<%=link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-light mt-3" if (is_logged_in) && (@user == current_user) || current_user.admin? %>
	<h2 class = "text-on-grape text-center mt-4"> <%= @user.username %>s Notes</h2>
</div>
<%= render 'articles/article' %>
<div id = "page-content">
	<div class = "apple_pagination">
		<%= will_paginate @articles, :container => false  %>
	</div>
</div>